/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nbutt' at '2/3/17 5:20 PM' with Gradle 2.14.1
 *
 * @author nbutt, @date 2/3/17 5:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
